# Generated by Django 3.0.6 on 2020-05-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate_Messaging_A00',
            fields=[
                ('dateTimeStamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Collaborate_Messaging_A00_Rec', models.AutoField(primary_key=True, serialize=False)),
                ('messageType', models.CharField(choices=[('POST', 'Post'), ('REPLY', 'Reply')], db_column='Message_Type', default='POST', max_length=10)),
                ('message', models.TextField()),
                ('parentPostId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Collaborate_Messaging_A00')),
            ],
        ),
    ]
