# Generated by Django 3.0.6 on 2020-05-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborate_messaging_a00',
            name='id',
        ),
        migrations.AddField(
            model_name='collaborate_messaging_a00',
            name='messageId',
            field=models.AutoField(db_column='Collaborate_Messaging_A00_Rec', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborate_messaging_a00',
            name='parentPostId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Collaborate_Messaging_A00'),
        ),
    ]
