# Generated by Django 3.0.6 on 2020-05-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200513_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborate_messaging_a00',
            name='parentPostId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Collaborate_Messaging_A00'),
        ),
    ]
