# Generated by Django 3.0.6 on 2020-05-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200513_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborate_messaging_a00',
            old_name='Collaborate_Messaging_A00_Rec',
            new_name='messageId',
        ),
    ]
