# Generated by Django 3.0.6 on 2020-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborate_Messaging_A00',
            new_name='Post',
        ),
    ]
