# Generated by Django 3.0.6 on 2020-05-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200513_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='messageType',
            field=models.CharField(choices=[(1, 'Post'), (2, 'Reply')], db_column='Message_Type', default='PST', max_length=10),
        ),
    ]
